### ISSUE TITLE
出现 http: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by w123dog** [Unknwon/macaron#31]
好像是调用 ctx.JSON 或者 ctx.Status 的时候，shell会打印出来。
http: multiple response.WriteHeader calls 在 Go\src\net\http\server.go 的 WriteHeader 中。
修复下

**Comment by Unknwon** [comment]
说明你在一个请求流程里调用了2次响应方法，要看你的代码。

**Comment by w123dog** [comment]
哦，是我的错，关闭吧

**Comment by Unknwon** [comment]
@w123dog 错误的地方找到了？
