### ISSUE TITLE
建议增加QueryTrim

### ISSUE THREAD

**Issue by mocos** [Unknwon/macaron#37]
strings.TrimSpace(ctx.Query("name")) 这样太麻烦了

**Comment by Unknwon** [comment]
多谢提议，已经增加！

**Comment by mocos** [comment]
// QueryTirm querys and trims spaces form parameter.
func (ctx *Context) QueryTirm(name string) string {
	return strings.TrimSpace(ctx.Query(name))
}

写错了? QueryTirm  --> QueryTrim

**Comment by Unknwon** [comment]
我错了。。。:joy: 已修复
