### ISSUE TITLE
Random 404

### ISSUE THREAD

**Issue by mephux** [Unknwon/macaron#38]
I have been using macaron for a production app for awhile and I'm getting 404's if i click links too quickly.

**Comment by Unknwon** [comment]
Hi @mephux , thanks your feedback!

To make debug easier, are you running the latest version from GitHub `master` with `0.5.2.0210`?

**Comment by mephux** [comment]
@Unknwon I ungraded my version and the problem seems fixed. It must have been something in an older cut of the software. Closing.
