### ISSUE TITLE
Setting Response Headers

### ISSUE THREAD

**Issue by limianwang** [Unknwon/macaron#42]
I am fairly new at Go and Macaron, but I have a question regarding setting response headers.

```go
func main() {
  m := macaron.Classic()
  m.Use(func(ctx *macaron.Context) {
    ctx.Resp.Header.Set('key', value);
  })
}
```

But I get an error: `ctx.Resp.Header.Set undefined (type func() http.Header has no field or method Set)`

What have I done wrong?

Thanks!

**Comment by Unknwon** [comment]
Hi, based on the docs: https://gowalker.org/net/http#Header . Header is a map, and do not have `Set` method.

**Comment by Unknwon** [comment]
What is your Go version and macaron version?

**Comment by Unknwon** [comment]
OK, I see the problem. `Header()` is an method, not a field. So use it as follows:

```go
ctx.Resp.Header().Set("Content-Description", "File Transfer")
```

**Comment by limianwang** [comment]
Great. I will give it a try later and let you know. Thanks!

**Comment by limianwang** [comment]
Weird, I am still getting this error:

```bash
ctx.Resp.Header().set undefined (type http.Header has no field or method set)
```

and my code is:

```go
ctx.Resp.Header().set("X-Test-Header", "aa")
```

**Comment by limianwang** [comment]
It is not complaining anymore. I'll do some test to make sure it's properly written, but thanks again!

**Comment by Unknwon** [comment]
@limianwang you should really learn basics of Go before start doing anything!

**Comment by limianwang** [comment]
Yeah. That's what i'm doing by pocking around. :) Do you have any suggestions?

**Comment by Unknwon** [comment]
@limianwang Based on your user name I suppose you can read Chinese, my video tutorials should help you out: https://github.com/Unknwon/go-fundamental-programming

**Comment by limianwang** [comment]
Yes, I will watch it now. 我先看看。 谢谢！

**Comment by Unknwon** [comment]
If you have further questions, you can post them on http://golanghome.com/ or join QQ group 371440803 , I'm there :bowtie:

**Comment by limianwang** [comment]
@Unknwon Ok sounds good. I don't have QQ, but do you have other groups? (ie. slack/gitter?)

**Comment by Unknwon** [comment]
https://gitter.im/Unknwon this link should work.
