### ISSUE TITLE
路由功能，可选匹配有BUG？

### ISSUE THREAD

**Issue by lauyoume** [Unknwon/macaron#45]
/user/list/?:page:int 这种无法匹配到/usr/list/, 只能匹配到 /usr/list/123 这种

**Comment by Unknwon** [comment]
感谢反馈！最新自己写了一套完整的 macaron 路由层，在 `mtre` 分支中，本地测试已经不会出现您的问题，希望您可以拉取下该代码再次测试！

**Comment by Unknwon** [comment]
Hi，代码已经推送到master分支！

**Comment by Unknwon** [comment]
Hi，基于你提供的信息的bug已经修复，此 issue 目前会保持关闭状态，如有异议可以重新开启 :smile:
