### ISSUE TITLE
POST JSON 数据绑定验证后如何在自己的控制器中得到Post上来的数据

### ISSUE THREAD

**Issue by xiaocongWang** [Unknwon/macaron#47]
我看了源代码，binding.Json() 执行后  是把请求里的body存入到context中了 ，我该怎么去重新拿到这些数据

**Comment by Unknwon** [comment]
你好，我觉得文档的描述挺清晰的。。http://macaron.gogs.io/docs/middlewares/binding.html :mask:

**Comment by Unknwon** [comment]
唔。。先关闭了。。要是有什么不懂的可以继续交流。。
