### ISSUE TITLE
Dynamic subdomains?

### ISSUE THREAD

**Issue by piotrrojek** [Unknwon/macaron#48]
Is there a way to use dynamic subdomains in Macaron?
E.g. calling sub1.mydomain.com would trigger its handler, and sub2.mydomain.com another - but the thing is to match these subdomains dynamically.

**Comment by Unknwon** [comment]
Hi @piotrrojek ,

I'm not sure what exactly do you mean by `dynamically`, but there is middleware called [switcher](https://github.com/macaron-contrib/switcher) allows you use one HTTP port and one program to serve multiple sites(based on domain name in request header).

The real example of this middleware can be found in [Gogs Web](https://github.com/gogits/gogsweb/blob/master/gogsweb.go#L97).

As a result, when you visit [macaron.gogs.io](http://macaron.gogs.io) and [gogs.io](http://gogs.io), they are two different sites.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
