### ISSUE TITLE
Broken Context

### ISSUE THREAD

**Issue by dariusc93** [Unknwon/macaron#50]
While reviewing my code (before moving it to another framework) I noticed that the context are somewhat broken. When you attempt to redirect, it does complete the redirection but it does not yield at that point but continue on down the nest until the end of that specific scope, which does cause many problems.

**Comment by Unknwon** [comment]
Thanks your feedback!

But do you have an example about the use case you're talking?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
