### ISSUE TITLE
现在的路由是不是有BUG？

### ISSUE THREAD

**Issue by activego** [Unknwon/macaron#51]
现在的路由是不是有BUG？

以前我这样的Post的请求是生效的，在url里面还可以跟参数 
```go
m.Post("/searchCategory2Json/:category:string", searchCategoryJsonAction)
```

但是最近更新了macaron之后，这样的Post请求就无法走到searchCategoryJsonAction方法里去了

**Comment by activego** [comment]
发现2天前又有更新，我刚更新了，现在代码可以正常路由到我的searchCategoryJsonAction方法里去了

但是有一个新BUG

我实际的测试用例的url是 searchCategory2Json/Sg==
但是在searchCategoryJsonAction方法里我ctx.Params("category")得到的居然是 Sg=
少了一个等号
请看下这个是不是新BUG？

**Comment by Unknwon** [comment]
这个问题已经通过QQ解决，先行关闭。若有疑问可继续开启讨论~ :beer:
