### ISSUE TITLE
access to expvars?

### ISSUE THREAD

**Issue by Dieterbe** [Unknwon/macaron#52]
normally in Go code you can just `import _ "expvar"` which adds a http handler directly , listening on `/debug/vars` (see http://golang.org/pkg/expvar/)

However, when using macaron, this route is hidden and 404's.

i have used github.com/macaron-contrib/toolbox which solves a similar problem for `/debug/pprof` but I couldn't find the solution for expvars.

thanks.

**Comment by Unknwon** [comment]
Hi @Dieterbe , hope follow code helps!

```go
package main

import (
	_ "expvar"
	"net/http"

	"github.com/Unknwon/macaron"
)

func main() {
	m := macaron.New()
	m.Use(func(ctx *macaron.Context) {
		if ctx.Req.URL.Path == "/debug/vars" {
			http.DefaultServeMux.ServeHTTP(ctx.Resp, ctx.Req.Request)
		}
	})
	m.Run()
}
```

Also, if you want, I can make it to be a part of official middleware, but the real code is short and simple though. :grinning:

**Comment by Dieterbe** [comment]
works splendidly. thank you
